import numpy as np
import matplotlib.pyplot as plt
from copy import deepcopy
from cattle import Ranch
from params import params

def run_monte_carlo_optimization(budget=30000, n_simulations=50):
    print(f"--- Starting Monte Carlo Optimization (Budget: ${budget}) ---")
    
    price_cow = params['price_vaca_preniada']
    price_bull = params['price_toro']
    
    results = {}
    
    # Iterate through possible number of cows
    # We assume we need at least 1 bull.
    # Logic: 1 bull per ~25 cows (4% rule), but minimum 1.
    
    max_possible_cows = int(budget / price_cow)
    
    for n_cows in range(1, max_possible_cows + 1):
        # Determine required bulls
        n_bulls = max(1, int(np.ceil(n_cows * params['min_bull_percentage'])))
        
        # Calculate Initial Investment
        initial_cost = (n_cows * price_cow) + (n_bulls * price_bull)
        
        # Check Budget
        if initial_cost > budget:
            continue
            
        print(f"Testing configuration: {n_cows} Cows + {n_bulls} Bulls (Cost: )")
        
        final_net_worths = []
        
        for i in range(n_simulations):
            # Create isolated parameters for this run
            sim_params = deepcopy(params)
            sim_params['initial_cows'] = n_cows
            sim_params['initial_toros'] = n_bulls
            # We don't set initial_capital to the budget, because the simulation 
            # tracks cash flow relative to 0. The 'cost' is the initial investment.
            # We want to maximize the final value generated by that investment.
            
            ranch = Ranch(sim_params)
            
            # Run simulation
            for _ in range(sim_params['months_to_simulate']):
                ranch.run_month()
            
            # Collect Final Net Worth
            final_net_worths.append(ranch.history['worth'][-1])
            
        results[n_cows] = {
            'cost': initial_cost,
            'bulls': n_bulls,
            'net_worths': final_net_worths,
            'mean_worth': np.mean(final_net_worths),
            'median_worth': np.median(final_net_worths),
            'std_dev': np.std(final_net_worths)
        }

    return results

def plot_results(results):
    cows = sorted(results.keys())
    means = [results[c]['mean_worth'] for c in cows]
    costs = [results[c]['cost'] for c in cows]
    
    # Extract data for boxplot
    data_to_plot = [results[c]['net_worths'] for c in cows]
    
    fig, ax1 = plt.subplots(figsize=(12, 7))

    # Boxplot for Net Worth distribution
    ax1.boxplot(data_to_plot, positions=cows, widths=0.6, patch_artist=True, 
                boxprops=dict(facecolor="lightblue"))
    ax1.set_xlabel('Initial Number of Pregnant Cows')
    ax1.set_ylabel('Final Net Worth ($)', color='blue')
    ax1.tick_params(axis='y', labelcolor='blue')
    ax1.set_title('Monte Carlo Optimization: Initial Herd Size vs. Final Net Worth')
    
    # Plot Initial Cost on secondary axis
    ax2 = ax1.twinx()
    ax2.plot(cows, costs, color='red', marker='o', linestyle='--', label='Initial Cost')
    ax2.set_ylabel('Initial Investment ($)', color='red')
    ax2.tick_params(axis='y', labelcolor='red')
    
    # Add grid and legend
    ax1.grid(True, alpha=0.3)
    fig.legend(loc='upper left', bbox_to_anchor=(0.1, 0.9))
    
    plt.tight_layout()
    plt.savefig("monte_carlo_optimization.png")
    print("Optimization plot saved to 'monte_carlo_optimization.png'")

    # Find best option
    best_cow_count = max(results, key=lambda x: results[x]['mean_worth'])
    best = results[best_cow_count]
    print(f"\n*** BEST CONFIGURATION ***")
    print(f"Cows: {best_cow_count}")
    print(f"Bulls: {best['bulls']}")
    print(f"Initial Cost: ${best['cost']}")
    print(f"Expected Final Net Worth: ${best['mean_worth']:,.2f}")

if __name__ == "__main__":
    data = run_monte_carlo_optimization()
    plot_results(data)
